name: meals
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0-255.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fried-rice_2515189.png"  # Fixed typo in extension
  # Optional adaptive icons for Android
  # adaptive_icon_foreground: "assets/icon_foreground.png"
  # adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/fried-rice_2515189.png
    - assets/asparagus-3304997_1280.jpg 
    - assets/burger-500054_1280.jpg 
    - assets/CucumberTomatoFetaSalad3-scaled.jpg 
    - assets/curry.jpg 
    - assets/curry.webp 
    - assets/fried-rice_2515189.png 
    - assets/mousse.jpg 
    - assets/pancake-3529653_1280.jpg 
    - assets/schnitzel-3279045_1280.jpg 
    - assets/shoffle.jpg 
    - assets/spicy-spaghetti-arrabbiata.jpg 
    - assets/toast-3532016_1280.jpg